      - name: Build IPA
        script: |
          # Get Team ID from provisioning profile
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE=$(find "$PROFILES_HOME" -name "*.mobileprovision" | head -1)
          TEAM_ID=$(security cms -D -i "$PROFILE" | grep -A1 "<key>TeamIdentifier</key>" | tail -1 | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
          echo "Using Team ID: $TEAM_ID"
          
          # Create export options plist with Team ID
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          # Build archive with Team ID
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            archive
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa
