workflows:
  ios-app-store-release:
    name: iOS App Store Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.saad.trendmadinah
      vars:
        XCODE_PROJECT: ios/App/App.xcodeproj
        XCODE_SCHEME: App
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Install pods
        script: |
          cd ios/App
          pod install
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
