workflows:
  capacitor_ios_release:
    name: Capacitor iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 20.19.0
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.saad.trendmadinah"
    scripts:
      - name: Extract zip files
        script: |
          unzip -o client.zip -d .
          unzip -o server.zip -d .
          unzip -o shared.zip -d .
          unzip -o ios.zip -d .
          ls -la
      - name: Install npm dependencies
        script: npm ci
      - name: Build web assets
        script: |
          mkdir -p attached_assets/generated_images
          echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" | base64 -d > attached_assets/generated_images/minimalist_islamic_geometric_logo_green_and_gold.png
          cat > postcss.config.js << 'EOF'
          export default { plugins: {} }
          EOF
          cat > vite.build.config.js << 'EOF'
          import { defineConfig } from "vite";
          import react from "@vitejs/plugin-react";
          import tailwindcss from "@tailwindcss/vite";
          import path from "path";
          export default defineConfig({
            plugins: [react(), tailwindcss()],
            resolve: {
              alias: {
                "@": path.resolve(process.cwd(), "client", "src"),
                "@shared": path.resolve(process.cwd(), "shared"),
                "@assets": path.resolve(process.cwd(), "attached_assets"),
              },
            },
            root: path.resolve(process.cwd(), "client"),
            build: {
              outDir: path.resolve(process.cwd(), "dist/public"),
              emptyOutDir: true,
            },
          });
          EOF
          npx vite build --config vite.build.config.js
      - name: Sync Capacitor iOS project
        script: |
          sed -i '' "s/platform :ios, '14.0'/platform :ios, '15.0'/" ios/App/Podfile
          npx cap sync ios
      - name: Increment build number
        script: |
          cd ios/App
          BUILD_NUMBER=$(($(date +%s) / 60))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" App/Info.plist
          echo "Build number set to: $BUILD_NUMBER"
      - name: Install CocoaPods
        script: |
          cd ios/App
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 14.0/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' App.xcodeproj/project.pbxproj
          pod install --repo-update
      - name: Set up keychain and fetch signing files
        script: |
          keychain initialize
          
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY=$(cat /tmp/cert_key.pem)
          
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@env:CERTIFICATE_PRIVATE_KEY \
            --strict-match-identifier
          
          keychain add-certificates
          
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_PATH=$(find "$PROFILES_HOME" -name "*.mobileprovision" | head -1)
          PROFILE_UUID=$(security cms -D -i "$PROFILE_PATH" | plutil -extract UUID raw -)
          TEAM_ID=$(security cms -D -i "$PROFILE_PATH" | plutil -extract TeamIdentifier.0 raw -)
          PROFILE_NAME=$(security cms -D -i "$PROFILE_PATH" | plutil -extract Name raw -)
          
          echo "$TEAM_ID" > /tmp/TEAM_ID
          echo "$PROFILE_NAME" > /tmp/PROFILE_NAME
          echo "$PROFILE_UUID" > /tmp/PROFILE_UUID
          
          echo "Team ID: $TEAM_ID"
          echo "Profile Name: $PROFILE_NAME"
          echo "Profile UUID: $PROFILE_UUID"
      - name: Configure code signing for App target only
        script: |
          TEAM_ID=$(cat /tmp/TEAM_ID)
          PROFILE_NAME=$(cat /tmp/PROFILE_NAME)
          
          cd ios/App
          
          xcode-project use-profiles --project Pods/Pods.xcodeproj || true
          xcode-project use-profiles --project App.xcodeproj
          
          /usr/libexec/PlistBuddy -c "Set :objects:*:buildSettings:CODE_SIGNING_ALLOWED NO" Pods/Pods.xcodeproj/project.pbxproj 2>/dev/null || true
      - name: Build IPA
        script: |
          TEAM_ID=$(cat /tmp/TEAM_ID)
          PROFILE_NAME=$(cat /tmp/PROFILE_NAME)
          
          cat > /tmp/export_options.plist << PLISTEOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROFILE_NAME</string>
              </dict>
          </dict>
          </plist>
          PLISTEOF
          
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --config Release \
            --export-options-plist /tmp/export_options.plist \
            --archive-directory build \
            --ipa-directory build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
